"""Coordinate transforms and OpenCV projection utilities."""

from spatial_reconstruction.geometry.projection import (
    MissingCameraError,
    backproject_pixels,
    backproject_valid_pixels,
    depth_confidence_valid_mask,
    project_camera_points,
)
from spatial_reconstruction.geometry.static_scene import (
    AxisAlignedBounds,
    ColoredPointCloud,
    DepthScaleObservation,
    MarkerDepthScaleEstimate,
    PointFilteringStats,
    StaticSceneRerunExportSummary,
    StaticSceneRunSummary,
    backproject_static_depth,
    confidence_percentile_threshold,
    estimate_marker_depth_scale,
    radius_overlap_fraction,
    select_bundles_for_target_times,
    select_keyframe_bundles,
    voxel_downsample,
    write_colored_ply,
)
from spatial_reconstruction.geometry.transforms import (
    camera_points_to_world,
    invert_rigid_transform,
    transform_points,
    validate_rigid_transform,
    world_points_to_camera,
)

__all__ = [
    "MissingCameraError",
    "AxisAlignedBounds",
    "ColoredPointCloud",
    "DepthScaleObservation",
    "MarkerDepthScaleEstimate",
    "PointFilteringStats",
    "StaticSceneRerunExportSummary",
    "StaticSceneRunSummary",
    "backproject_pixels",
    "backproject_static_depth",
    "backproject_valid_pixels",
    "camera_points_to_world",
    "depth_confidence_valid_mask",
    "confidence_percentile_threshold",
    "estimate_marker_depth_scale",
    "invert_rigid_transform",
    "project_camera_points",
    "radius_overlap_fraction",
    "select_bundles_for_target_times",
    "select_keyframe_bundles",
    "transform_points",
    "validate_rigid_transform",
    "voxel_downsample",
    "world_points_to_camera",
    "write_colored_ply",
]
